/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group6.Book_Store;

/**
 *
 * @author naugy
 */
public class Book {
    
    private String isbn;
    private String name;
    private String description;
    private String price;
    private String author;
    private String genre;
    private String publisher;
    private int yearPublished;
    private int copiesSold;

    //you must include a no-args constructor when you have a POST or PUT method
    public Book(){ }

    public Book(String isbn, String name, String description, String price, Spring author, String genre, String publisher, int yearPublished, int copiesSold) {
        this.isbn = isbn;
        this.name = name;
        this.description = description;
        this.price = price;
        this.author = author;
        this.genre = genre;
        this.publisher = publisher;
        this.yearPublished = yearPublished;
        this.copiesSold = copiesSold;

    }

    //getters and setters, equals() and hashCode() generated by IDE
}


