/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group6.Book_Store;

/**
 *
 * @author naugy
 */
public class Book {
    
    private String isbn;
    private String name;
    private String description;

    //you must include a no-args constructor when you have a POST or PUT method
    public Book(){ }

    public Book(String isbn, String name, String description, ) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    //getters and setters, equals() and hashCode() generated by IDE
}


